---
# When a push is made to a branch, deploy an instance of the app using
# that branch. 
# The deployed url will be <branchname>.<domain>

name: Deploy branch
on: 
  - pull_request
  # (pull_request_target get fired on external contributer pull requests)
  # - pull_request_target
jobs:
  deploy-pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare runner with ssh keys
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          set -x
          mkdir -p ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          ssh-keyscan $DOKKU_HOST >> ~/.ssh/known_hosts
      - name: Create dokku app for branch if dosent already exist using dokku apps:create
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          set -x
          echo $GITHUB_CONTEXT
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          echo Creating dokku app ${{ github.actor }}-${{ github.head_ref }}
          ssh dokku@$DOKKU_HOST -C "dokku apps:create ${{ github.actor }}-${{ github.head_ref }} | true"
          echo The url will be ${{ github.actor }}-${{ github.head_ref }}.pcpink.co.uk
          ssh dokku@$DOKKU_HOST -C "dokku git:set ${{ github.actor }}-${{ github.head_ref }} deploy-branch ${{ github.head_ref }}"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy branch ${{ github.head_ref }} to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dokku-host: ${{ secrets.DOKKU_HOST }}
          app-name: ${{ github.actor }}-${{ github.head_ref }}
          remote-branch: ${{ github.head_ref }}
