---
# When a push is made to a branch, deploy an instance of the app using
# that branch. 
# The deployed url will be <branchname>.<domain>

name: Deploy branch
on: push
jobs:
  deploy-pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Prepare runner with ssh keys & create dokku app
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DOKKU_HOST: ${{ secrets.DOKKU_HOST }}
        run: |
          mkdir -p ~/.ssh
          eval `ssh-agent -s`
          ssh-add - <<< "$SSH_PRIVATE_KEY"
          ssh-keyscan $DOKKU_HOST >> ~/.ssh/known_hosts
          echo Creating dokku app
          ssh dokku@$DOKKU_HOST -C "dokku apps:clone angular-deploy angular-deploy-staging"
